services:
  app-v1:
    build: 337405469571.dkr.ecr.ap-southeast-2.amazonaws.com/secure-app:v1
    container_name: app-version1
    environment:
      - APP_VERSION=v1
    expose:
      - "5000"
    restart: always

  app-v2:
    image: 337405469571.dkr.ecr.ap-southeast-2.amazonaws.com/secure-app:v1
    container_name: app-version2
    environment:
      - APP_VERSION=v2
    expose:
      - "5000"
    restart: always

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy-gateway
    ports:
      - "80:80"
    volumes:
      - ./:/etc/nginx/conf.d/
    depends_on:
      - app-v1
    restart: always
