name: Secure Payment Gateway

on:
  push:
    branches: [ main ]

env:
  ECR_REPOSITORY: secure-app
  IMAGE_TAG: v1
  AWS_REGION: ap-southeast-2

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push the Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: | 
          docker build --no-cache -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG . 
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Copy docker-compose.yml & nginx.conf to EC2
        uses: appleboy/scp-action@v0.1.7
        with: 
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "docker-compose.yml, nginx.conf"
          target: "~/"

      - name: Execute Smart Blue-Green Switchover
        uses: appleboy/ssh-action@v1.0.3
        with: 
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            aws ecr get-login-password --region ap-southeast-2 | docker login --username AWS --password-stdin 337405469571.dkr.ecr.ap-southeast-2.amazonaws.com
            cd ~

            docker-compose pull

            CURRENT_TARGET=$(grep -o 'app-v[1-2]' nginx.conf)

            if [ "$CURRENT_TARGET" = "app-v1" ]; then
              NEW_TARGET="app-v2"
              OLD_CONTAINER="app-version1"
            else
              NEW_TARGET="app-v1"
              OLD_CONTAINER="app-version2"
            fi

            docker compose up -d $NEW_TARGET 
            sleep 5

            sed -i "s/proxy_pass http:\/\/$CURRENT_TARGET:5000;/proxy_pass http:\/\/$NEW_TARGET:5000;/" nginx.conf

            docker exec nginx-container-app-v1 nginx -s reload

            docker stop $OLD_CONTAINER    
